name: digitalearthpacific
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy>=0.24.0
  - cftime>=1.6.4
  - jupyterlab=4.1.5
  - jupyter-book=1.0.3
  - matplotlib-base>=3.10.3
  - obstore>=0.7.0
  - odc-stac>=0.3.2
  - planetary-computer>=1.0.0
  - python=3.11
  - gdown
  - xclim>=0.57.0
  - zarr>=3.1.0
